// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/admin/roles" | "/dashboard/admin/roles/[id]" | "/dashboard/admin/settings" | "/dashboard/admin/users" | "/dashboard/admin/users/[id]" | "/dashboard/admin/vehicle-types" | "/dashboard/admin/vehicle-types/[vehicleTypeId]" | "/dashboard/admin/vehicle-types/[vehicleTypeId]/maintenance-checks/[checkId]" | "/dashboard/interventions" | "/dashboard/notifications" | "/dashboard/profile" | "/dashboard/statistics" | "/dashboard/vehicles" | "/dashboard/vehicles/[id]" | "/login" | "/signup"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/dashboard/admin/roles": {}
  "/dashboard/admin/roles/[id]": { "id": string; }
  "/dashboard/admin/settings": {}
  "/dashboard/admin/users": {}
  "/dashboard/admin/users/[id]": { "id": string; }
  "/dashboard/admin/vehicle-types": {}
  "/dashboard/admin/vehicle-types/[vehicleTypeId]": { "vehicleTypeId": string; }
  "/dashboard/admin/vehicle-types/[vehicleTypeId]/maintenance-checks/[checkId]": { "vehicleTypeId": string; "checkId": string; }
  "/dashboard/interventions": {}
  "/dashboard/notifications": {}
  "/dashboard/profile": {}
  "/dashboard/statistics": {}
  "/dashboard/vehicles": {}
  "/dashboard/vehicles/[id]": { "id": string; }
  "/login": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
